"""Unit test for EMAN2's fast-LST parsing — a pure function, testable without
the eman2 conda env or any real EMAN2 output."""
from stw.adapters.eman2 import parse_lst

_LST_CONTENT = """#LSX
# generated by stw test
# 42
3\tparticles.hdf\t{}
7\tparticles.hdf\t{}
12\tparticles.hdf\t{}
"""


def test_parse_lst_extracts_indices(tmp_path):
    lst = tmp_path / "ptcls_cls01.lst"
    lst.write_text(_LST_CONTENT)
    assert parse_lst(lst) == [3, 7, 12]


def test_parse_lst_skips_blank_lines(tmp_path):
    lst = tmp_path / "ptcls_cls00.lst"
    lst.write_text("#LSX\n# comment\n# 10\n1\tp.hdf\t{}\n\n2\tp.hdf\t{}\n")
    assert parse_lst(lst) == [1, 2]


def test_parse_lst_empty_class(tmp_path):
    lst = tmp_path / "ptcls_cls02.lst"
    lst.write_text("#LSX\n# comment\n# 10\n")
    assert parse_lst(lst) == []
